#!/bin/sh
# -----------------------------------------------------------------------------
#
# NAME
#     CMD - Wsl Operation Manager
#
# DESCRIPTION
#     Tool for executing one or multiple operations on the system. Default ones
#     are actually defined to clean up the system from sensitive or undesirable 
#     information and preparing it as a base for cloning, or instantiation of 
#     WSL instances, or to shrink the instance disk.
#     User can add new operations by filling the formatted set_operation_dictionary
#     string argument and implement them on the custom_operations section.
#
# USAGE
#     CMD --help
#         This help
#     CMD --version
#         It will display this script current version
#     CMD --list
#         It will list all supported operations and mark the default one with the
#         asterisk '*'.
#     CMD [--operations <operation-list>]... [--<key>=<val>]...
#         [--yes] [--strict] [--ignore-errors] [--verbose]  
#
#     '--operations'
#         Allow to set a comma separated list of operations where amongst the
#         actual names of the operations. Specials keywords 'default' and 'all'
#         are also recognized. Their meaning is obvious.
#         For the list of all supported operations use the '--list' option.
#     '--<key>=<val>'
#         Operation argument defined by the code 'arguments_get'
#         User can pass arguments to opérations by setting them on command line.
#         Array can be manage with pattern like '--arg-my-variable'. This variable
#         could be retreive on operation by requiering the following code:
#         'arguments_get $(arguments_key_format "arg" "my_variable")'
#     '--yes'
#         Never ask for permission - run non-interactively - otherwise in some
#         circumstances (for your own safety) program will refuse to continue
#         until you type 'yes'.
#     '--strict'
#         Abort the run of this program if system is not recognized.
#     '--verbose'
#         Print executed commands and show their output.
#
# EXAMPLES
#     CMD --operations default --yes
#         Run all default operations but only if explicitly replied 'YES'
#     CMD --operations default,-backup-files
#         Run all default operations EXCEPT the backup-files
#     CMD --operations backup-files,shell-history
#         Run only these two operations
#     CMD --operations all --yes
#         Run all default operations - no questions asked
#     CMD --operations user-account --username=anonymous
#         Run the create user operation with username as argument
#     CMD --operations ini-cfg --file=wsl.conf --ini-network-hostname=k8s \
#         --ini-automount-options='"metadata,uid=1000"'
#         Set the hostname in section network and options in the automount
#         section on the wsl.conf INI file
#
# -----------------------------------------------------------------------------

set -e

# shellcheck disable=SC1007
SCRIPTDIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)   
CMD=$(basename "$0")
VERSION="2.3.7"

# -----------------------------------------------------------------------------
#                     Operations Trigger Definitions
# -----------------------------------------------------------------------------

custom_operations() {

    # here are declared all operations - keep the following format:
    #   <operation>:<default>:<comment>
    # for each operation there should be corresponding function:
    #   op_<operation-with_underscores>
    set_operation_dictionary '
        system-update           :0: Update System
        backup-files            :1: Remove editor backup files from the guest
        crash-data              :1: Remove the crash data generated by kexec-tools
        customize               :1: Allow user defined default actions.
        logfiles                :1: Remove many log files from the guest
        mail-spool              :1: Remove email from the local mail spool directory
        package-manager-cache   :1: Remove package manager cache
        passwd-backups          :1: Remove /etc/passwd- and similar backup files
        prune-docker            :1: Remove all unused containers, networks, images and anonymous volumes 
        shell-history           :0: Remove the .history file
        tmp-files               :1: Remove temporary files
        user-account            :0: Set the default user account in the guest (require --username=<name>)
        ini-cfg                 :0: Fill INI configuration file (require --file=<file> [--ini-<key>=<value>]*)
        '


    # shellcheck disable=SC2329
    op_system_update(){
        run_op() {
            echo "+ ${*}"
            "$@"
        }

        if command -v apk >/dev/null; then
            run_op apk --update-cache upgrade
        elif command -v apt-get >/dev/null; then
            DEBIAN_FRONTEND=noninteractive
            export DEBIAN_FRONTEND
            run_op apt-get -qy update
            run_op apt-get -qy \
                -o Dpkg::Options::="--force-confdef" \
                -o DPkg::Options::="--force-confold" \
                upgrade
            run_op apt-get -qy autoremove
        elif command -v dnf >/dev/null; then
            run_op dnf -y --best upgrade
        elif command -v yum >/dev/null; then
            run_op yum -y --obsoletes update
        elif command -v zypper >/dev/null; then
            run_op zypper --non-interactive update --auto-agree-with-licenses
        elif command -v pkg >/dev/null; then
            # TODO: FreeBSD returns error when no update is available...
            run_op freebsd-update --not-running-from-cron fetch || true
            run_op freebsd-update --not-running-from-cron install || true
        else
            warn "No package manager found - SKIP"
        fi
    }

    # User defined operation
    # shellcheck disable=SC2329
    op_customize() (
        if [ -x "$SCRIPTDIR/$CMD-customize" ]; then
            run_op "$SCRIPTDIR/$CMD-customize" cleanup
        else
            echo "Not implemented"
        fi
    )

    # shellcheck disable=SC2329
    op_backup_files() (
        run_op() {
            echo "+ ${*}"
            "$@"
        }
        # do not search on mount partitions
        flag="-xdev"
        # shellcheck disable=SC2185
        if find --version 2>&1 | grep -q GNU; then
            flag="-mount"
        fi
        run_op find / "$flag" \( -name '*.bak' -o -name '*~' \) -delete || true
    )

    # shellcheck disable=SC2329
    op_crash_data() (
        run_op() {
            echo "+ ${*}"
            "$@"
        }
        run_op rm -rvf /var/crash/* /var/log/dump/*
    )

    # shellcheck disable=SC2329
    op_logfiles() (
        run_op() {
            echo "+ ${*}"
            "$@"
        }

        # Delete all .gz and rotated file
        run_op find /var/log -type f -regex ".*\.gz$" --delete
        run_op find /var/log -type f -regex ".*\.[0-9]$" --delete
        # set other file to empty
        run_op find /var/log/ -type f -exec cp /dev/null {} \;
    )

    # shellcheck disable=SC2329
    op_mail_spool() (
        run_op() {
            echo "+ ${*}"
            "$@"
        }
        run_op rm -rvf /var/spool/mail/* /var/mail/*
    )

    # shellcheck disable=SC2329
    op_package_manager_cache() (
        run_op() {
            echo "+ ${*}"
            "$@"
        }

        if command -v apk >/dev/null; then
            run_op apk cache clean
        elif command -v apt-get >/dev/null; then
            run_op apt-get clean
        elif command -v apt >/dev/null; then
            run_op apt clean
        elif command -v dnf >/dev/null; then
            run_op dnf clean all --enablerepo=\*
        elif command -v yum >/dev/null; then
            run_op yum clean all --enablerepo=\*
        elif command -v zypper >/dev/null; then
            run_op zypper clean --all
        elif command -v pkg >/dev/null; then
            run_op pkg clean --all --yes
        fi

        for d in \
            /var/cache/apt/archives/ \
            /var/cache/dnf/ \
            /var/cache/yum/ \
            /var/cache/zypp* \
            /var/cache/apk/*; do
            if [ -d "$d" ]; then
                run_op find "$d" -type f -delete
            fi
        done
        if command -v snap; then
            snap list --all | awk '/disabled/{print $1, $3}' |
                while read -r snapname revision; do
                    run_op snap remove "$snapname" --revision="$revision"
                done
        fi
    )

    # shellcheck disable=SC2329
    op_passwd_backups() (
        run_op() {
            echo "+ ${*}"
            "$@"
        }

        run_op rm -vf \
            /etc/group- \
            /etc/gshadow- \
            /etc/passwd- \
            /etc/shadow- \
            /etc/subuid- \
            /etc/subgid- \
            ;
    )

    # shellcheck disable=SC2329
    op_tmp_files() (
        run_op() {
            echo "+ ${*}"
            "$@"
        }

        for d in /tmp/ /var/tmp/; do
            if [ -d "$d" ]; then
                run_op find "$d" -maxdepth 1 -mindepth 1 -exec rm -rvf '{}' \;
            fi
        done
    )

    # shellcheck disable=SC2329
    op_shell_history() (
        run_op() {
            echo "+ ${*}"
            "$@"
        }

        run_op rm -vf \
            /home/*/.history \
            /root/.history \
            /home/*/.*_history \
            /root/.*_history \
            ;
    )

    # shellcheck disable=SC2329
    op_prune_docker() (
        run_op() {
            echo "+ ${*}"
            "$@"
        }
        if command -v docker >/dev/null; then
            run_op docker system prune --all --volumes --force
        fi
    )

  # shellcheck disable=SC2329
    op_ini_cfg() {
        file="$(arguments_get file)"
        arg_pattern="ini"
        if [ ! -n "$file" ]; then
            warn "No file specified in arguments - SKIP"
            return 2
        fi

        inicfg_args=
        keys="$(arguments_keys_starts_with "$arg_pattern")"
        for ini_key in $keys; do
            # transform to xpath
            key=$(arguments_key_format "$ini_key" "$arg_pattern" ".")
            inicfg_args="$inicfg_args $key=$(arguments_get "$ini_key")"
        done
        # shellcheck disable=SC2086
        system_set_inicfg "$file" $inicfg_args
    }

    # shellcheck disable=SC2329
    op_user_account() {
        run_op() {
            echo "+ ${*}"
            "$@"
        }

        os_id=$(system_distribution)
        username=$(arguments_get username)
        if [ ! -n "$username" ]; then
            warn "No username specified in arguments - SKIP"
            return 2
        fi

        if id "$username" >/dev/null 2>&1; then
            printf "[!] User %s already exists !\n" "$username"
            return 2
        fi

        grpname="$username"
        grpid=1000
        case "$os_id" in

            alpine)
                # install / configure sudo
                if ! command -v sudo >/dev/null; then
                    for pkg in sudo openssl shadow; do
                        if ! apk info 2>/dev/null | grep "$pkg" >/dev/null; then
                            run_op apk --no-cache add "$pkg"
                        fi
                    done
                    if ! grep sudo /etc/group; then
                        run_op addgroup --gid 65530 sudo
                    fi
                    run_op sed -i 's/# *%sudo/%sudo/' /etc/sudoers
                fi
                run_op addgroup --gid "$grpid" "$grpname"
                run_op adduser --disabled-password --gecos '' \
                    --uid 1000 -G "$grpname" "$username"
                run_op adduser "$username" sudo

                # Initialize user password:
                echo "Please create password for user $username"
                userencpass="$(/usr/bin/openssl passwd -1)"
                run_op usermod --password "$userencpass" "$username"
                return 0
                ;;

            ubuntu)
                # release >ubuntu-23 already has user ubuntu with uid:gid set to 1000:1001
                if id -u ubuntu >/dev/null 2>&1; then
                    run_op deluser --remove-home ubuntu >/dev/null
                fi
                if grep ':1000:' /etc/group >/dev/null; then
                    grpid=1001
                fi
                run_op addgroup --gid "$grpid" "$grpname"
                run_op adduser --quiet --disabled-password --gecos '' \
                    --uid 1000 --gid "$grpid" "$username"
                run_op usermod -aG sudo "$username"

                # Initialize user password:
                echo "Please create password for user $username"
                userencpass="$(/usr/bin/openssl passwd -1)"
                run_op usermod --password "$userencpass" "$username"
                return 0
                ;;

            #altlinux)
            #debian|devuan) ;;
            #fedora|centos|rhel|almalinux|ol|rocky|amzn) return 0 ;;
            #opensuse*|sles|sled) return 0 ;;
            #freebsd) return 0 ;;
            *)
                warn "This system ('${os_id:-UNKNOWN}') is not supported!"
                exit 2
                ;;
        esac
    }

}

# -----------------------------------------------------------------------------
# GENERIC PART - Edit following lines with care and only if needed ...
# -----------------------------------------------------------------------------

terminal(){
    
    SETCOLOR_ON_OK=
    SETCOLOR_ON_FAILURE=
    SETCOLOR_ON_HIGHLIGHT=
    SETCOLOR_ON_HIGHLIGHT2=
    SETCOLOR_ON_COMMAND=
    SETCOLOR_OFF=


    banner() (
        printf "%s\n\n" "
                            _ 
            __      __ ___ | |  ___   _ __   ___ 
            \ \ /\ / // __|| | / _ \ | '_ \ / __|   Wslctl System Preparation Tool
             \ V  V / \__ \| || (_) || |_) |\__ \   2021-2025, wslctl Project
              \_/\_/  |___/|_| \___/ | .__/ |___/   Version $VERSION
                                     |_|" | sed 's/^[ ]\{12\}//'
    )

    usage()( sed "/^$/q;1d;s/^#//;s/CMD/$CMD/g;s/^ -*//g;" "$0" | sed '$d' )
    help() ( printf "${SETCOLOR_ON_COMMAND}[!] try help: %s${SETCOLOR_OFF}\n" "$CMD --help" >&2 )
    msg() ( printf "${SETCOLOR_ON_HIGHLIGHT2}[%s]${SETCOLOR_OFF}: ${*}\n" "$CMD" )
    err_and_exit() { err "$@"; exit 1; }

    err() (
        {
            printf "${SETCOLOR_ON_HIGHLIGHT2}[%s]${SETCOLOR_OFF}" "$CMD"
            printf " ${SETCOLOR_ON_FAILURE}%s${SETCOLOR_OFF}\n" "[!] ERROR: ${*}"
        } >&2
    )
    
    warn() (
        {
            printf "${SETCOLOR_ON_HIGHLIGHT2}[%s]${SETCOLOR_OFF}" "$CMD"
            printf " ${SETCOLOR_ON_FAILURE}%s${SETCOLOR_OFF}\n" "[!] WARNING: ${*}"
        } >&2
    )

    ask() (
        if ! is_option yes ; then

            case "$1" in
                yes)
                    _reply=''
                    while [ -z "$_reply" ]; do
                        printf "%s (${SETCOLOR_ON_COMMAND}%s${SETCOLOR_OFF})? " \
                            "Do you really want to continue" \
                            "'y/yes/Y/YES'"
                        read -r _reply

                        case "$_reply" in
                            y | Y | yes | YES) return 0 ;;
                        esac
                    done
                    return 1 ;;

                proceed)
                    printf "${SETCOLOR_ON_FAILURE}%s\n%s\n%s\n\n${SETCOLOR_OFF}" \
                        "[!] BEWARE: This will erase some system data!" \
                        "[!] If you are not certain what this program does - " \
                        "    try help: ${CMD} --help\n\n"
                    if ! ask yes; then
                        msg "ABORTED"
                        exit 0
                    fi ;;

                force)
                    if ! ask yes; then
                        msg "Aborded"
                        exit 0
                    fi
                    warn "We will continue on the best-effort basis..." ;;
            esac
        fi
    )

    # inspired here:
    # https://unix.stackexchange.com/questions/485070/all-round-100-portable-terminal-color-support-check
    # and modified for alpine's busybox (which supports colors)
    is_terminal_colorful() {
        { command -v tput && { tput setaf || tput AF; } } >/dev/null 2>&1
        # shellcheck disable=SC2181
        if [ $? -eq 0 ]; then
            return 0
        fi
        # naive workaround for systems without ncurses
        test "$TERM" = 'xterm-256color'
        return $?
    }

    set_terminal_colors() {
        SETCOLOR_ON_OK='\033[0;32;1m'         # green
        SETCOLOR_ON_FAILURE='\033[0;31;1m'    # red
        SETCOLOR_ON_HIGHLIGHT='\033[0;32;1m'  # green
        SETCOLOR_ON_HIGHLIGHT2='\033[0;36;1m' # cyan
        SETCOLOR_ON_COMMAND='\033[0;33;1m'    # yellow
        SETCOLOR_OFF='\033[0m'
    }

    is_terminal_colorful && set_terminal_colors || true
}

system(){

    # detect the OS: alpine|altlinux|debian|ubuntu|fedora|centos|rhel|...
    system_distribution() {
        
        if [ -f /etc/os-release ]; then
            ID=
            # shellcheck disable=SC1091
            . /etc/os-release
            os_id=$(echo "$ID" | tr '[:upper:]' '[:lower:]')
        elif [ -f /etc/centos-release ]; then
            os_id='centos'
        elif [ -f /etc/redhat-release ]; then
            os_id='rhel'
        else
            os_id=$(uname | tr '[:upper:]' '[:lower:]')
        fi
        echo "$os_id"
    }

    # this will try to guess the system it is running on and if it is supported by
    # this script
    system_check_supported() {
        os_id=$(system_distribution)

        # return success if listed here:
        case "$os_id" in
        alpine | altlinux) return 0 ;;
        debian | ubuntu | devuan) return 0 ;;
        fedora | centos | rhel | almalinux | ol | rocky | amzn) return 0 ;;
        opensuse* | sles | sled) return 0 ;;
        freebsd) return 0 ;;
        esac

        warn "This system ('${os_id:-UNKNOWN}') is not supported!"
        if is_option 'strict'; then
            err_and_exit "System check failed while 'strict' option used - ABORT"
        else
            ask force
            return 0
        fi
    }

    system_cmd() {
        if is_option 'verbose'; then
            printf "${SETCOLOR_ON_HIGHLIGHT2}[%s]${SETCOLOR_OFF}:" "$CMD"
            printf " ${SETCOLOR_ON_COMMAND}%s${SETCOLOR_OFF}\n"  "${*}"
        fi
        if ! "$@" && ! is_option 'ignore-errors'; then
            err_and_exit "Command failed - ABORT"
        fi
    }

    system_sanity_check() {
        # test the sanity of an awk implementation
        if ! system_is_posix_awk; then
            warn "The currently used awk command does not support POSIX:"
            printf "\n%s\n\n" "$(awk -W version 2>&1 || true)"
            printf "[!] NOTE: Install an alternative (e.g. gawk) or some operations may be skipped!\n\n"
        fi
    }

    # trivial test of awk command capabilities and compliance
    system_is_posix_awk() (
        res=$(echo 'abcABC   xyz123.' | awk '{ sub(/[[:upper:]]+[[:space:]]+[[:alnum:]]+/, ""); print;}')
        if [ "${res}" = 'abc.' ]; then
            return 0
        fi
        return 1
    )


    # arg(s): <ini_file> [<section.key=value> ]+
    system_set_inicfg() {
        filename="$1"
        shift
        # normalize line spacing
        if [ ! -f "$filename" ]; then
            touch "$filename"
        fi
        cfg=$(printf '%s\n\n' "$(sed '/^$/d' "$filename" | sed '2,$ s/^\[/\n\[/g')")

        while [ $# -gt 0 ]; do
            section_key_value="$1"
            section=$(echo "$section_key_value" | sed 's;\..*$;;')
            key=$(echo "$section_key_value" | sed 's;^.*\.;;' | sed 's;=.*;;')
            value=$(echo "$section_key_value" | sed 's;[^=]*=;;')

            if printf "%s" "$cfg" | grep -qF "[$section]"; then
                if printf "%s" "$cfg" | sed -n "/^\[$section\]$/,/^$/p" | grep -q "^$key"; then
                    cfg=$(printf "%s" "$cfg" | sed "/^\[$section\]$/,/^$/ s/^$key\s*=.\+/$key=$value/")
                else
                    cfg=$(printf "%s" "$cfg" | sed "/^\[$section\]$/,/^$/ s/^$/$key=$value\n/")
                fi
                cfg=$(printf '%s\n\n' "$cfg")
            else
                cfg=$(printf '%s\n\n[%s]\n%s=%s\n\n' "${cfg}" "$section" "$key" "$value")
            fi
            shift
        done

        printf "%s" "$cfg" >"$filename"
    }

    system_check_supported && system_sanity_check || true
}

options() {
    _cli_options=

    # arg: <option>
    set_option() {
        _cli_options="$_cli_options $1"
    }

    # arg: <option>
    # it will simply check if option from argument was set (inside _OPTIONS)
    is_option() {
        for _option in ${_cli_options}; do
            if [ "$1" = "$_option" ]; then
                return 0
            fi
        done
        return 1
    }

}

operations(){
    operation_dictionary=
    operations_to_call=

    # arg: multiline string
    # here are declared all operations - keep the following format:
    #   <operation>:<default>:<comment>
    # for each operation there should be corresponding function:
    #   op_<operation-with_underscores>
    set_operation_dictionary(){
        operation_dictionary="$(echo "$1" | sed 's/^[ \t]*//')"
    }

    # arg: all|default|<op>
    # it will return (based on argument):
    #   list of all operations
    #   list of all default operations
    #   operation if exists
    #   empty string if operation does not exist
    get_operation_dictionary() (
        case "$1" in
        all) parse_operation_dictionary normal | cut -d: -f1 ;;
        default|cleanup) parse_operation_dictionary normal | sed -n 's/^\(.*\):1$/\1/p' ;;
        *) parse_operation_dictionary normal | sed -n "s/^\(${1}\):[0-1]\$/\1/p" ;;
        esac
    )

    # arg: [normal|summary]
    # if used with argument 'summary' then it will print out summary of supported
    # operations - otherwise it will output parseable: <op>:<default>
    parse_operation_dictionary() {
        echo "$operation_dictionary" | awk -v output="${1:-normal}" '
        BEGIN {  FS = ":"; count=0; }
        {
            if ($0 == "") next;

            op = $1;
            sub(/^[ ]*/, "", op);
            sub(/[ ]*$/, "", op);

            default_op = $2;
            sub(/^[ ]*/, "", default_op);
            sub(/[ ]*$/, "", default_op);

            comment = $3;
            sub(/^[ ]*/, "", comment);
            sub(/[ ]*$/, "", comment);

            count++;
            ops[count] = op;
            ops_comment[op] = comment;
            ops_default[op] = default_op;
        }
        END {
            if (output == "normal"){
                for (i = 1; i <= count; i++) {
                    op = ops[i];
                    printf("%s:%s\n", op, ops_default[op]);
                }
            } else if (output == "summary") {
                max_length = 0;
                for (i = 1; i <= count; i++) {
                    if (length(ops[i]) > max_length)
                        max_length = length(ops[i]);
                }

                for (i = 1; i <= count; i++) {
                    op = ops[i];
                    if (ops_default[op] == "1")
                        asterisk = "*";
                    else
                        asterisk = " ";
                    extra_spaces_count = max_length - length(op);
                    extra_spaces = "";
                    for (s = 1; s <= extra_spaces_count; s++)
                        extra_spaces = extra_spaces " ";
                    printf("%s %s%s %s\n", asterisk, op, extra_spaces, ops_comment[op]);
                }
            }
        }'
    }

    list_operation_dictionary() {
        printf "LIST OF ALL SUPPORTED OPERATIONS:\n\n"
        printf "(asterisk '*' designates a default operation)\n\n"
        parse_operation_dictionary summary
    }

    # arg: <list-of-operations>
    add_operations(){
        operations_to_call="$operations_to_call $(echo "$1" | tr ',' ' ')"
    }

    # arg: none
    run_operations() {
        if [ ! -n "$operations_to_call" ]; then
            err_and_exit "No operation specified - EXIT"
        fi

        _whitelist=
        _blacklist=
        for _op in ${operations_to_call}; do
            # is it blacklisted operation?
            _black_op=$(echo "$_op" | sed -n 's/^-\(.*\)/\1/p')
            if [ -n "$_black_op" ]; then
                # add excluded operation(s) to the blacklist
                _ops=$(get_operation_dictionary "$_black_op")

                if [ -n "$_ops" ]; then
                    _blacklist="${_blacklist} ${_ops}"
                else
                    err_and_exit "Unsupported operation expr.: ${_op}"
                fi
            else
                # extend the whitelist for requested operation(s)
                _ops=$(get_operation_dictionary "$_op")
                if [ -n "$_ops" ]; then
                    _whitelist="${_whitelist} ${_ops}"
                else
                    err_and_exit "Unsupported operation expr.: ${_op}"
                fi
            fi
        done

        # deduplicate and sort the both lists
        _whitelist=$(echo "$_whitelist" | tr ' ' '\n' | sort -u)
        _blacklist=$(echo "$_blacklist" | tr ' ' '\n' | sort -u)

        _ops=
        _max_oplength=0
        for _op in $(get_operation_dictionary all); do
            # if the operation is NOT whitelisted/requested then skip it
            if ! echo "$_whitelist" | tr ' ' '\n' | grep -q "^${_op}\$"; then
                continue
            fi

            # if the operation is NOT blacklisted then add it to the final list
            if ! echo "$_blacklist" | tr ' ' '\n' | grep -q "^${_op}\$"; then
                # find the longest operation name
                if [ "${#_op}" -gt "$_max_oplength" ]; then
                    _max_oplength="${#_op}"
                fi
                _ops="${_ops} ${_op}"
            fi
        done

        # execute requested operations one by one
        for _op in ${_ops}; do
            _op_func=$(echo "$_op" | tr '-' '_')
            if is_option 'verbose'; then
                # run verbosely
                printf "${SETCOLOR_ON_HIGHLIGHT}%s${SETCOLOR_OFF}:" "Run operation"
                printf " ${SETCOLOR_ON_COMMAND}%s${SETCOLOR_OFF}\n" "${_op}"

                # if-wrap
                if eval "op_${_op_func}"; then
                    _op_func_return_code=$?
                else
                    _op_func_return_code=$?
                fi

                case "${_op_func_return_code}" in
                0)
                    printf "${SETCOLOR_ON_HIGHLIGHT}%s${SETCOLOR_OFF}" "Result"
                    printf " ... ${SETCOLOR_ON_OK}%s${SETCOLOR_OFF}\n\n" "OK"
                    ;;
                1)
                    printf "${SETCOLOR_ON_HIGHLIGHT}%s${SETCOLOR_OFF}" "Result"
                    printf " ... ${SETCOLOR_ON_FAILURE}%s${SETCOLOR_OFF}\n\n" "FAILED"
                    ;;
                2)
                    printf "${SETCOLOR_ON_HIGHLIGHT}%s${SETCOLOR_OFF}" "Result"
                    printf " ... ${SETCOLOR_ON_FAILURE}%s${SETCOLOR_OFF}\n\n" "SKIPPED"
                    ;;
                esac
            else
                # run non-verbosely
                printf "${SETCOLOR_ON_HIGHLIGHT}%s${SETCOLOR_OFF}:" "Run operation"
                printf " ${SETCOLOR_ON_COMMAND}%-*s${SETCOLOR_OFF} ... " "$_max_oplength" "${_op}"

                # if-wrap
                if _op_func_output=$(eval "op_${_op_func}" 2>&1); then
                    _op_func_return_code=$?
                else
                    _op_func_return_code=$?
                fi

                # shellcheck disable=SC2059
                case "${_op_func_return_code}" in
                0) printf "${SETCOLOR_ON_OK}OK${SETCOLOR_OFF}\n" ;;
                2)
                    printf "${SETCOLOR_ON_FAILURE}SKIPPED${SETCOLOR_OFF}\n"
                    echo "$_op_func_output"
                    ;;
                1)
                    printf "${SETCOLOR_ON_FAILURE}FAILED${SETCOLOR_OFF}\n"
                    echo "$_op_func_output"
                    ;;
                esac
            fi
        done
    }

}

arguments(){
    arguments_keys=

    # simulate simple associative array on posix
    # arguments_set toto 2
    # value=$(arguments_get toto)

    # arg: key value
    arguments_set () { 
        if [ -n "$1" ]; then
            key="$(echo "$1" | sed 's/\-/_/g')"
            eval "__aa__$key='$2'"
            arguments_keys="$arguments_keys $key"
        fi
    }

    # arg: key
    arguments_get(){ 
        key="$(echo "$1" | sed 's/\-/_/g')"
        eval echo "\$__aa__$key"
    }

    # arg: pattern
    arguments_keys_starts_with(){
        result=
        pattern="$(echo "$1-" | sed 's/\-/_/g')"
        for key in $arguments_keys; do
            case "$key" in
                "$pattern"*) result="$result $key" ;;
                *) ;;
            esac
        done
        echo "$result"
    }

    # arg: key start_pattern sep_char
    arguments_key_format(){
        pattern="$(echo "$2-" | sed 's/\-/_/g')"
        echo "$1" | sed "s/^$pattern//" | sed "s/_/${3:-_}/g"
    }
   
}

main(){

    terminal
    system
    operations
    options
    arguments
    custom_operations

    while :; do
        case $1 in
            -h|-\?|--help) banner; usage; exit ;;
            -i|--ignore-errors) set_option ignore-errors ;;
            -l|--list) list_operation_dictionary; exit ;;
            -o|--operations)
                if [ -n "$2" ]; then add_operations "$2"; shift;
                else err_and_exit "'--operations' requires a non-empty option argument"
                fi ;;
            --operations=?*) add_operations "${1#*=}" ;;
            -s|--strict) set_option strict ;;
            -v|--verbose) set_option verbose ;;
            -y|--yes) set_option yes ;;
            -V|--version) echo "$VERSION"; exit ;;
            --*=*) arguments_set "$(echo "$1" | sed 's/^\-\-//;s/=.*//')" "${1#*=}";;
            --) shift; break ;;
            -?*) err "Unknown option (ignored): $1"; exit 1 ;;
            *) break # Default case: If no more options then break out of the loop.
        esac
        shift
    done
    
    run_operations
}

main "$@"
